//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermPaperDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cCarriage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cCarriage()
        {
            this.cPlaces = new HashSet<cPlace>();
        }
    
        public int Id { get; set; }
        public int CarriageNumber { get; set; }
        public int TrainId { get; set; }
        public int TypeId { get; set; }
    
        public virtual vTrain vTrain { get; set; }
        public virtual cType cType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cPlace> cPlaces { get; set; }
    }
}
