//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermPaperDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cStationInRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cStationInRoute()
        {
            this.cTickets = new HashSet<cTicket>();
            this.cTickets1 = new HashSet<cTicket>();
        }
    
        public int Id { get; set; }
        public int StationId { get; set; }
        public int RouteId { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
    
        public virtual cRoute cRoute { get; set; }
        public virtual cStation cStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTicket> cTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTicket> cTickets1 { get; set; }
    }
}
