//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermPaperDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cTicket
    {
        public int Id { get; set; }
        public string PassangerFisrtName { get; set; }
        public string PassangerLastName { get; set; }
        public string PassangerPatronymic { get; set; }
        public decimal Price { get; set; }
        public bool Returned { get; set; }
        public int TrainId { get; set; }
        public int PlaceId { get; set; }
        public int DepartureStationId { get; set; }
        public int ArrivalStationId { get; set; }
    
        public virtual cPlace cPlace { get; set; }
        public virtual cStationInRoute cStationInRoute { get; set; }
        public virtual cStationInRoute cStationInRoute1 { get; set; }
        public virtual vTrain vTrain { get; set; }
    }
}
