//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermPaperDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IS02_SellingRailwayTicketsEntities : DbContext
    {
        public IS02_SellingRailwayTicketsEntities()
            : base("name=IS02_SellingRailwayTicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cCarriage> cCarriages { get; set; }
        public virtual DbSet<cPlace> cPlaces { get; set; }
        public virtual DbSet<cRoute> cRoutes { get; set; }
        public virtual DbSet<cStation> cStations { get; set; }
        public virtual DbSet<cStationInRoute> cStationInRoutes { get; set; }
        public virtual DbSet<cTicket> cTickets { get; set; }
        public virtual DbSet<cType> cTypes { get; set; }
        public virtual DbSet<vTrain> vTrains { get; set; }
    }
}
